name: Trigger auto deployment for ab-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ab-app-AutoDeployTrigger-e929eea6-2cde-477d-aa14-f30751c555e6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ABAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ABAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ABAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.ABAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ABAPP_REGISTRY_PASSWORD }}
          containerAppName: ab-app
          resourceGroup: AB-TST
          imageToBuild: Andy170780/ab-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


